name: opencv-choco

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependency
      shell: powershell
      run: choco install 7zip.commandline

    - name: pack choco
      shell: powershell
      run: choco pack
      
    - name: install choco
      shell: powershell
      run: choco install opencv --source .
